### PR TITLE
Use ADL syntax

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
👍

**Comment by SylvainCorlay** [comment]
Merged. Super minor thing (if we end up using cookiecutters to generate this kind of bindings). In xleaflet, I had put the `using` statements right above the function calls.

**Comment by martinRenou** [comment]
What is the difference ?

**Comment by SylvainCorlay** [comment]
None, just that I think we will end up generating this type of code :)

**Pull request merged**
